// lib/plan-export.js
// Turn a Genie campaign plan into a document the owner can keep — with zero
// external libraries. Word: an HTML blob with a .doc extension (Word opens it
// natively). PDF: a print window the browser's "Save as PDF" turns into a file.
// Both are free, offline, and need nothing installed.

function esc(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Build the shared printable HTML body for a plan.
function planHtml(plan) {
  const rows = (plan.schedule || []).map(
    (r) => `<tr><td style="white-space:nowrap;font-weight:600">${esc(r.when)}</td><td>${esc(r.task)}</td><td style="white-space:nowrap;color:#555">${esc(r.channel)}</td></tr>`
  ).join("");
  const steps = (plan.steps || []).map(
    (s, i) => `<li><b>${esc(s.title)}</b>${s.detail ? `<br><span style="color:#333">${esc(s.detail)}</span>` : ""}</li>`
  ).join("");
  const assets = (plan.assets || []).map(
    (a) => `<div style="margin:0 0 12px"><div style="font-size:12px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.04em">${esc(a.name)}</div><div style="white-space:pre-wrap;margin-top:2px">${esc(a.copy)}</div></div>`
  ).join("");
  const date = new Date(plan.createdAt || Date.now()).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  return `<div style="font-family:Georgia,'Times New Roman',serif;color:#111;max-width:720px;margin:0 auto;line-height:1.55">
    <div style="font-size:12px;color:#888;letter-spacing:.06em;text-transform:uppercase">Marketing Genie, ${esc(plan.business || "your business")}</div>
    <h1 style="font-size:26px;margin:6px 0 2px">${esc(plan.title)}</h1>
    <div style="color:#888;font-size:13px;margin-bottom:18px">${esc(plan.label || "")} · ${date}</div>
    ${plan.goal ? `<p style="font-size:15px"><b>Goal.</b> ${esc(plan.goal)}</p>` : ""}
    ${plan.summary ? `<p style="font-size:15px">${esc(plan.summary)}</p>` : ""}
    ${steps ? `<h2 style="font-size:18px;margin:22px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px">The plan</h2><ol style="padding-left:20px">${steps}</ol>` : ""}
    ${assets ? `<h2 style="font-size:18px;margin:22px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px">Ready-to-use copy</h2>${assets}` : ""}
    ${rows ? `<h2 style="font-size:18px;margin:22px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px">Schedule</h2>
      <table style="width:100%;border-collapse:collapse;font-size:14px" cellpadding="6">
        <thead><tr style="text-align:left;border-bottom:2px solid #333"><th>When</th><th>Task</th><th>Channel</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>` : ""}
    <p style="margin-top:26px;color:#aaa;font-size:12px">Generated by Marketing Genie.</p>
  </div>`;
}

function fileStub(plan) {
  return String(plan.title || plan.label || "genie-plan").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "genie-plan";
}

// Download as a Word document (HTML with a Word wrapper + .doc extension).
export function downloadWord(plan) {
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(plan.title)}</title></head><body>${planHtml(plan)}</body></html>`;
  const blob = new Blob(["﻿", html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `${fileStub(plan)}.doc`;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

// Open a clean print window; the browser's "Save as PDF" produces the PDF.
export function printPdf(plan) {
  const w = window.open("", "_blank");
  if (!w) return false;
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(plan.title)}</title>
    <style>@media print{@page{margin:18mm}} body{margin:24px}</style></head>
    <body onload="setTimeout(function(){window.print()},250)">${planHtml(plan)}</body></html>`);
  w.document.close();
  return true;
}
